### ISSUE TITLE
how to set permissions

### ISSUE THREAD

**Issue by NeftaliAcosta** [scottybo/LinkedIn-API-client-v2#2]
How do I access the token to save it in the database?

![image](https://user-images.githubusercontent.com/15948880/62408657-b00c6b00-b591-11e9-8371-07028d832bdc.png)

```
public function callback(){
 $token = $this->cliente->getAccessToken();
 var_dump($token);
}
```

**Comment by NeftaliAcosta** [comment]
![image](https://user-images.githubusercontent.com/15948880/62408713-94ee2b00-b592-11e9-98b9-1a392c3f00cd.png)

**Comment by scottybo** [comment]
Hi @NeftaliAcosta - this package isn't supported (as mentioned on the README). It works, and I actively use it, but I don't have the time/resources to help other people use it
